[M1386-2]
data-mermaid/mermaid-api pull request #110
Opened 2020-09-03 20:58 UTC by tienhoah

2020-09-03 20:59 UTC, tienhoah commented
![](https://github.trello.services/images/mini-trello-icon.png) [Collect - allow PIT transect length to have one decimal, e.g., 10.5m length (currently, integer only)](https://trello.com/c/OFDr06ry/1386-collect-allow-pit-transect-length-to-have-one-decimal-eg-105m-length-currently-integer-only)

2021-01-21 18:19 UTC, saanobhaai requested changes

2021-01-21 18:19 UTC, saanobhaai commented on src/api/ingest/fishbelt_serializer.py
> +    data__fishbelt_transect__len_surveyed = serializers.DecimalField(max_digits=4, decimal_places=1)
Looks like you've done fishbelt and benthic PIT; but we should also do benthic LIT and habitatcomplexity

2021-01-21 18:19 UTC, saanobhaai commented on src/api/migrations/0008_auto_20200903_2034.py
> +            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)], verbose_name='transect
I think we shouldn't put model-level validators on this; submission validations should take care of warnings

2021-01-21 18:19 UTC, saanobhaai commented on src/api/models/mermaid.py
> +                                    validators=[MinValueValidator(10), MaxValueValidator(100)],
See above -- I think we shouldn't put model-level validators on this

2021-01-29 16:26 UTC, saanobhaai requested changes
@tienhoah all looks good; just a couple of cleanup comments. Then I'll likely update the migrations based on others that have happened in the meantime.

2021-01-29 16:26 UTC, saanobhaai commented on src/api/models/mermaid.py
> +    len_surveyed = models.DecimalField(max_digits=4, decimal_places=1,
fix spacing/alignment

2021-01-29 16:26 UTC, saanobhaai commented on src/api/ingest/benthicpit_serializer.py
> +    # data__benthic_transect__len_surveyed = serializers.IntegerField(min_value=0)
delete commented line here and below

2021-02-01 21:13 UTC, merged