[M1195] Added Benthic LIT and Habitat Complexity ingest
data-mermaid/mermaid-api pull request #111
Opened 2020-09-15 21:16 UTC by gridcell

2020-09-15 21:17 UTC, gridcell commented
![](https://github.trello.services/images/mini-trello-icon.png) [add LIT and habitatcomplexity ingestion schema csvs](https://trello.com/c/KyDCO2vT/1195-add-lit-and-habitatcomplexity-ingestion-schema-csvs)

2020-12-21 15:28 UTC, saanobhaai requested changes

2020-12-21 15:28 UTC, saanobhaai commented on src/api/ingest/benthiclit_serializer.py
> +        return row.get("data__benthic_transect__sample_time") or "00:00:00"
We shouldn't default to midnight; should just leave this as `None`

2020-12-21 15:28 UTC, saanobhaai commented on src/api/ingest/benthiclit_serializer.py
> +    data__benthic_transect__sample_time = serializers.TimeField(default="00:00:00")
Here and throughout the PR I think the default should just be `None`

2021-01-04 22:39 UTC, merged