M1475: Clean up the duplicate sample unit on submitted record save
data-mermaid/mermaid-api pull request #129
Opened 2021-02-25 19:41 UTC by gridcell

- Add a method to check after a submitted sample unit method has been updated to check for sample events that are the same and combine them

2021-02-25 19:42 UTC, gridcell commented
![](https://github.trello.services/images/mini-trello-icon.png) [handle merging/splitting sample events from submitted sample units](https://trello.com/c/51U9uMIF/1475-handle-merging-splitting-sample-events-from-submitted-sample-units)

2021-02-26 16:50 UTC, saanobhaai requested changes

2021-02-26 16:53 UTC, gridcell commented on src/api/utils/sample_units.py
> +    qry = qry.annotate(num_sample_events=Count("site"))
yeah you're right, I was going to go down the road of modifying that function overall but thought wasn't worth it.  Will change this up

2021-03-02 17:14 UTC, saanobhaai commented on src/api/utils/sample_units.py
> +    qry = qry.annotate(num_sample_events=Count("site"))
OK looks good -- but we need `> 1` not `> 0` right?

2021-03-29 19:30 UTC, merged