[M1612] Change bleaching percent data type to decimal
data-mermaid/mermaid-api pull request #211
Opened 2022-01-20 23:49 UTC by gridcell

- changes to models and ingest

2022-01-20 23:49 UTC, gridcell commented
![](https://github.trello.services/images/mini-trello-icon.png) [bleaching perc_cover columns - add support for numeric entries (currently only integer)](https://trello.com/c/KWvxwoEY/1612-bleaching-perccover-columns-add-support-for-numeric-entries-currently-only-integer)

2022-01-21 14:35 UTC, saanobhaai requested changes
Just a print statement

2022-01-21 14:35 UTC, saanobhaai commented on src/api/ingest/bleaching_serializer.py
> +        print(f"grouped_records: {grouped_records}")
remove

2022-01-21 14:35 UTC, saanobhaai commented on src/api/tests/test_sample_unit_method_obs.py
> +    assert pytest.approx(float(rows[3]["Soft coral (% cover)"]), 1) == pytest.approx(
Interesting. I'm sure it's right, but curious why `float` and not `Decimal` (and wouldn't that remove the need for the `approx`).

2022-01-28 18:06 UTC, merged