[M1595] Bleaching Validtors
data-mermaid/mermaid-api pull request #214
Opened 2022-02-04 01:24 UTC by gridcell

2022-02-04 01:25 UTC, gridcell commented
![](https://github.trello.services/images/mini-trello-icon.png) [Port Bleaching validations to v2](https://trello.com/c/rlLM2Bey/1595-port-bleaching-validations-to-v2)

2022-02-09 02:53 UTC, saanobhaai requested changes
Damned impressive.

2022-02-09 02:53 UTC, saanobhaai commented on src/api/submission/validations2/validators/generic.py
> +    NOT_POSITIVE_INTEGER = "not_postitive_integer"
spelling

2022-02-09 02:53 UTC, saanobhaai commented on src/api/submission/validations2/validators/quadrat_size.py
> +            if quadrat_size == 0:
`quadrat_size <= 0`?

2022-02-15 12:15 UTC, gridcell commented on src/api/submission/validations2/validators/__init__.py
> +from .generic import AllEqualValidator, DuplicateValidator, ListPositiveIntegerValidator, ListRequiredValidator, PositiveIntegerValidator, RequiredValidator
I prefer being explicit so I know what's being imported and works better with ide

2022-02-15 23:33 UTC, merged