[M1643] Run summary updates in simpleq worker
data-mermaid/mermaid-api pull request #226
Opened 2022-03-29 20:57 UTC by gridcell

- Added another container for elasticmq (SQS clone) for local testing
- Send summary updates that were being called in signals to simpleq jobs

2022-03-29 20:59 UTC, gridcell commented
![](https://github.trello.services/images/mini-trello-icon.png) [Run summary site and sample event updates in SimpleQ](https://trello.com/c/QF3DtWuB/1643-run-summary-site-and-sample-event-updates-in-simpleq)

2022-03-30 00:11 UTC, saanobhaai requested changes
Two trivial questions; also there's a conflict.

2022-03-30 00:11 UTC, saanobhaai commented on src/simpleq/queues.py
> +                "aws_access_key_id": os.environ["AWS_ACCESS_KEY_ID"],
Should we be getting these from settings, rather than directly from `os.environ`?

2022-03-30 00:11 UTC, saanobhaai commented on src/api/signals/__init__.py
> +from .summaries import * # noqa
2 spaces before inline comments is PEP no?

2022-03-30 21:45 UTC, merged