[M1607] Benthic Photo Quadrat Transect SQL Models
data-mermaid/mermaid-api pull request #241
Opened 2022-05-05 21:52 UTC by gridcell

2022-05-05 21:52 UTC, gridcell commented
![](https://github.trello.services/images/mini-trello-icon.png) [photo quadrat collection api endpoints](https://trello.com/c/mtl3iLeB/1607-photo-quadrat-collection-api-endpoints)

2022-05-17 21:33 UTC, saanobhaai requested changes

2022-05-17 21:33 UTC, saanobhaai commented on src/api/models/sql_models/benthicpqt.py
> +su_fields = BaseSUSQLModel.se_fields + [
Is this used, or extraneous (defined in `BenthicPhotoQuadratTransectSUSQLModel`)?

2022-05-17 21:33 UTC, saanobhaai commented on src/api/models/sql_models/benthicpqt.py
> +    # TODO: Does anything specific to Photo quadrat should be defined in this list
Discussed with Emily; I think we can leave this as is for now (and remove comment).

2022-05-18 01:06 UTC, merged