[M1566] make notes handling consistent and use SU notes for submit/ingest
data-mermaid/mermaid-api pull request #271
Opened 2022-08-18 17:30 UTC by saanobhaai

2022-08-18 17:30 UTC, saanobhaai commented
![](https://github.trello.services/images/mini-trello-icon.png) [audit and improve notes handling](https://trello.com/c/SWfqyswj/1566-audit-and-improve-notes-handling)

2022-08-18 19:27 UTC, gridcell requested changes

2022-08-18 19:27 UTC, gridcell commented on src/api/resources/sample_units/beltfishmethod.py
> +        # ReportField("sample_event_notes", "Sampling event notes"),
Remove?

2022-08-18 19:27 UTC, gridcell commented on src/api/resources/sample_units/beltfishmethod.py
> +        # ReportField("sample_event_notes", "Sampling event notes"),
Remove

2022-08-18 19:27 UTC, gridcell commented on src/api/resources/sample_units/benthiclitmethod.py
> +        # ReportField("sample_event_notes", "Sampling event notes"),
Remove

2022-08-18 19:27 UTC, gridcell commented on src/api/resources/sample_units/benthicphotoquadrattransectmethod.py
> +        # ReportField("sample_event_notes", "Sampling event notes"),
Remove

2022-08-18 19:27 UTC, gridcell commented on src/api/resources/sample_units/benthicpitmethod.py
> +        # ReportField("sample_event_notes", "Sampling event notes"),
Remove

2022-08-18 19:27 UTC, gridcell commented on src/api/resources/sample_units/bleachingquadratcollectionmethod.py
> +        # ReportField("sample_event_notes", "Sampling event notes"),
Remove

2022-08-18 19:27 UTC, gridcell commented on src/api/resources/sample_units/habitatcomplexitymethod.py
> +        # ReportField("sample_event_notes", "Sampling event notes"),
Remove

2022-08-18 19:27 UTC, gridcell commented on src/api/resources/summary_sample_event.py
> +        # ReportField("sample_event_notes", "Sample event notes"),
Remove

2022-08-18 19:27 UTC, gridcell commented on src/api/utils/summaries.py
> +    print(project_id, skip_test_project)
remove

2022-08-18 21:39 UTC, saanobhaai commented on src/api/ingest/benthicpit_serializer.py
> +        "Sample unit notes": "data__benthic_transect__notes",
I think it is... I can easily imagine a request for adding other notes fields...

2022-08-19 15:38 UTC, gridcell approved these changes

2022-08-19 18:59 UTC, merged