[M748] notification to CR owners on site/mr delete
data-mermaid/mermaid-api pull request #286
Opened 2022-09-25 14:37 UTC by saanobhaai

2022-09-25 14:37 UTC, saanobhaai commented
![](https://github.trello.services/images/mini-trello-icon.png) [notification to CR owners when referenced site/mr has been deleted](https://trello.com/c/zrVCUoeq/748-notification-to-cr-owners-when-referenced-site-mr-has-been-deleted)

2022-10-28 15:39 UTC, gridcell requested changes

2022-10-28 15:39 UTC, gridcell commented on src/api/resources/pmanagement.py
> +    def destroy(self, request, *args, **kwargs):
This should be a mixin since it's used in pmanagement and psite

2022-10-31 19:34 UTC, gridcell approved these changes

2022-10-31 19:34 UTC, merged