[M1700] CI/CD for new AWS architecture
data-mermaid/mermaid-api pull request #291
Opened 2022-10-03 20:23 UTC by aspcanada

2022-10-05 15:02 UTC, saanobhaai commented
![](https://github.trello.services/images/mini-trello-icon.png) [CI/CD for new AWS architecture](https://trello.com/c/fi9URuKV/1700-ci-cd-for-new-aws-architecture)

2022-10-05 15:35 UTC, saanobhaai requested changes
### EDIT
Just spoke with Dustin and am sorted out on versions/changelog. I'll create cards (for us) to handle those.

This looks good; I'm going to write out what's different from current circleci workflows, and we can figure out how to handle:

- both dev and prod: 
    - tag and push docker image
    - wait for deployment to complete successfully, then update version

- prod only:
    - update changelog (using trello api)

2022-10-12 20:31 UTC, aspcanada commented on .github/workflows/deploy-dev.yml
> +name: DeployCDKStacks
Correct. Any updates to `dev` branch will trigger a deploy - same as CircleCI

2022-10-12 20:35 UTC, aspcanada commented on .vscode/settings.json
> +{
I usually commit it to [share preferences](https://stackoverflow.com/questions/32964920/should-i-commit-the-vscode-folder-to-source-control) for those using vscode.

2022-10-13 18:28 UTC, merged