[M1839] Update summary models in batches
data-mermaid/mermaid-api pull request #369
Opened 2023-03-20 13:10 UTC by gridcell

In order to reduce memory usage during update summary models are updated in batches.  SQLModel  is filtered by sample event ids (10 sample events at a time).

2023-03-20 13:18 UTC, gridcell commented
![](https://github.trello.services/images/mini-trello-icon.png) [Reduce RAM usage when updating summary caches](https://trello.com/c/FOGlCh1l/1839-reduce-ram-usage-when-updating-summary-caches)

2023-03-21 22:32 UTC, saanobhaai requested changes
Brilliant.

2023-03-21 22:32 UTC, saanobhaai commented on src/api/models/sql_models/base.py
> +# sample_event_where = """se.id = '%(sample_event_id)s' :: uuid"""
cleanup comment

2023-03-21 22:32 UTC, saanobhaai commented on src/api/models/sql_models/base.py
> +project_where = """project.id = '%(project_id)s' :: uuid"""
ok but the spacing was actually nice when printing out for testing :-)

2023-03-21 22:32 UTC, saanobhaai commented on src/sqltables/query.py
> +        self.query.model_sql = self.query.model_sql.replace("<<__sql_table_args__>>", " AND ".join(["1 = 1", *[self.model.sql_args[field].sql for field  in sql_table_params]]))
Nice

2023-03-21 22:32 UTC, saanobhaai commented on src/api/utils/summary_cache.py
> +        _set_created_on(created_on, batch)
Does this need to be a separate function?

2023-03-21 22:32 UTC, saanobhaai commented on src/api/utils/summary_cache.py
> +            project_id=project_id, sample_event_id=sample_event_ids
Should `sql_table` arg be plural too, i.e. `sample_event_ids`?

2023-03-24 21:52 UTC, merged