[M119] Flatten Dictionary values in csv/excel reports
data-mermaid/mermaid-api pull request #413
Opened 2023-10-20 19:30 UTC by gridcell

2023-10-20 19:31 UTC, gridcell commented
![](https://github.trello.services/images/mini-trello-icon.png) [plan for dealing with nested arbitrary keys / BI / further calcs in csv/xlsx routes](https://trello.com/c/gkFHSh7k/119-plan-for-dealing-with-nested-arbitrary-keys-bi-further-calcs-in-csv-xlsx-routes)

2023-10-23 13:59 UTC, saanobhaai requested changes
Amazing, but you're right does add complexity!

2023-10-23 13:59 UTC, saanobhaai commented on src/api/reports/csv_report.py
> +    serialized_data = list(serialized_data)
Why not wrap the return value in `list()` within `get_data()`?

2023-10-23 13:59 UTC, saanobhaai commented on src/api/reports/rawcsv.py
> +    def data(self, fields, data, *args, **kwargs):
I may need to talk this one through... Wondering about 
- removing `self._apply_formatters()` from `stream`
- renaming `self.data()` to something like `self.formatted_data` (to separate out the formatting, allowing one in theory to be able to stream non-formatted data/headers)
- removing `self.stream_list` altogether, and adjusting `self.stream` header writing as necessary
but I'll bet there are reasons not to use this approach. Maybe it's a question of whether we need to preserve `self.stream` at all?

2023-10-23 13:59 UTC, saanobhaai commented on src/api/reports/csv_report.py
> +    return {new_key: [dic.get(key, None) for dic in column_records] for new_key, key in all_keys.items()}
In theory the `None` arg isn't necessary

2023-10-23 13:59 UTC, saanobhaai commented on src/api/reports/summary_report.py
> +    """Alan Coral Atlas covariates
`Allen`

2023-10-23 17:32 UTC, gridcell commented on requirements.txt
> +django-stubs==4.2.5
needed for python typing

2023-10-23 19:04 UTC, merged