[M1039] add omitted MR fields to summary SE views
data-mermaid/mermaid-api pull request #491
Opened 2024-09-17 20:04 UTC by saanobhaai

2024-09-17 20:04 UTC, saanobhaai commented
![](https://github.trello.services/images/mini-trello-icon.png) [add MR fields to summary SE views](https://trello.com/c/4OyOAOm8/1039-add-mr-fields-to-summary-se-views)

2024-09-18 16:56 UTC, gridcell requested changes

2024-09-18 16:56 UTC, gridcell commented on src/api/models/summary_sample_events.py
> +                management.project_id = '75ef7a5a-c770-4ca6-b9f8-830cab74e425' :: uuid
Need to swap out this id

2024-09-19 15:43 UTC, gridcell approved these changes

2024-09-19 15:43 UTC, merged