[M1170] add is_invalid filter to CR view
data-mermaid/mermaid-api pull request #530
Opened 2024-12-05 16:23 UTC by saanobhaai

2024-12-05 16:24 UTC, saanobhaai commented
![](https://github.trello.services/images/mini-trello-icon.png) [support invalid CR querying workflow](https://trello.com/c/UO75jmfp/1170-support-invalid-cr-querying-workflow)

2024-12-05 16:52 UTC, gridcell requested changes

2024-12-05 16:52 UTC, gridcell commented on src/api/resources/collect_record.py
> +    def filter_is_invalid(self, queryset, name, value):
You'll need to handle if is_invalid is `False`

2024-12-06 21:02 UTC, gridcell approved these changes

2024-12-06 21:02 UTC, merged